version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6399:6399
    restart: always
    volumes:
      - /root/fut_trading/redis/redis.conf:/etc/redis/redis.conf
      - /root/fut_trading/redis/data:/data
      - /root/fut_trading/redis/logs:/logs
    command: redis-server /etc/redis/redis.conf

  futures_trading_sys:
    image: futures_trading_sys:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    restart: on-failure
    depends_on:
      - redis